alias_map = {
    "Agricultural Engr Sciences Bld": 'Agricultural Engr Sciences Bld',
    "Architecture Building": 'Architecture Building',
    "Armory": 'Armory',
    "Art and Design Building": 'Art and Design Building',
    "Bevier Hall": 'Bevier Hall',
    "Burrill Hall": 'Burrill Hall',
    "Business Instructional Facility": 'Business Instructional Fac',
    "Campus Instructional Facility": 'Campus Instructional Facility',
    "Chemistry Annex": 'Chemistry Annex',
    "David Kinley Hall": 'David Kinley Hall',
    "Davenport Hall": 'Davenport Hall',
    "Education Building": 'Education Building',
    "Electrical and Computer Engineering Building": 'Electrical & Computer Eng Bldg',
    "Engineering Hall": 'Engineering Hall',
    "English Building": 'English Building',
    "Everitt Laboratory": 'Everitt Laboratory',
    "Flagg Hall": 'Flagg Hall',
    "Gregory Hall": 'Gregory Hall',
    "Henry Administration Bldg": 'Henry Administration Bldg',
    "Lincoln Hall": 'Lincoln Hall',
    "Literatures, Cultures, and Linguistics Building": 'Literatures, Cultures, & Ling',
    "Loomis Laboratory of Physics": 'Loomis Laboratory',
    "Mumford Hall": 'Mumford Hall',
    "Music Building=": 'Music Building',
    "Natural History Building": 'Natural History Building',
    "Newmark Civil Engineering Bldg": 'Newmark Civil Engineering Bldg',
    "Noyes Laboratory": 'Noyes Laboratory',
    "Psychology Building": 'Psychology Building',
    "Siebel Center for Comp Sci": 'Siebel Center for Comp Sci',
    "Sidney Lu Mechanical Engr Bldg": 'Sidney Lu Mech Engr Bldg',
    "Transporation Building": 'Transportation Building',
    "Turner Hall": 'Turner Hall',
    "Wohlers Hall": 'Wohlers Hall',
    "Wymer Hall": 'Wymer Hall',
    "Civil & Envir Eng Bldg" : 'Civil & Envir Eng Bldg',
    "Siebel Center for Design" : 'Siebel Center for Design'

}
